<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tc_registrasi_batal', function (Blueprint $table) {
            $table->integer('id_tc_registrasi')->nullable();
            $table->integer('no_registrasi')->nullable();
            $table->string('no_mr', 8)->nullable();
            $table->integer('kode_perusahaan')->nullable()->default(0);
            $table->integer('kode_kelompok')->nullable();
            $table->string('kode_dokter', 50)->nullable();
            $table->string('no_induk', 50)->nullable();
            $table->dateTime('tgl_jam_masuk')->nullable();
            $table->dateTime('tgl_jam_keluar')->nullable();
            $table->string('prioritas', 20)->nullable();
            $table->string('kode_bagian_masuk', 18)->nullable();
            $table->string('kode_bagian_keluar', 18)->nullable();
            $table->string('status_batal', 10)->nullable();
            $table->string('stat_pasien', 4)->nullable()->default('Lama');
            $table->tinyInteger('status_registrasi')->nullable();
            $table->integer('umur_old')->nullable();
            $table->dateTime('tgl_input')->nullable()->useCurrent();
            $table->integer('id_paket')->nullable();
            $table->string('no_jaminan', 50)->nullable();
            $table->string('nik', 50)->nullable();
            $table->integer('kode_pt')->nullable();
            $table->string('nama_pt')->nullable();
            $table->integer('status_man')->nullable();
            $table->string('no_jkn', 50)->nullable();
            $table->string('no_skp', 100)->nullable();
            $table->decimal('plafon_bpjs', 19, 4)->nullable();
            $table->string('diagnosa')->nullable();
            $table->integer('kode_plafon')->nullable();
            $table->integer('byr_selisih')->nullable();
            $table->integer('flag_daftar')->nullable();
            $table->integer('st_daftar_ulang')->nullable();
            $table->integer('status_milik')->nullable();
            $table->integer('kode_penanggung')->nullable();
            $table->decimal('umur', 18, 0)->nullable();
            $table->integer('id_dc_asal_pasien')->nullable();
            $table->integer('flag_dr_fis_perujuk')->nullable();
            $table->string('nama_karyawan', 70)->nullable();
            $table->integer('flag_status')->nullable();
            $table->string('noKartuPeserta', 50)->nullable();
            $table->dateTime('tglSep')->nullable();
            $table->dateTime('tglRujukan')->nullable();
            $table->string('noRujukan', 250)->nullable();
            $table->string('ppkRujukan', 50)->nullable();
            $table->string('ppkPelayanan', 50)->nullable();
            $table->string('jnsPelayanan', 2)->nullable();
            $table->text('catatan')->nullable();
            $table->string('kdDiag', 50)->nullable();
            $table->string('diagAwal', 250)->nullable();
            $table->string('poliTujuan', 50)->nullable();
            $table->string('klsRawat', 10)->nullable();
            $table->string('userInp', 50)->nullable();
            $table->string('noMr', 50)->nullable();
            $table->string('noSep', 250)->nullable();
            $table->integer('milike')->nullable();
            $table->string('jnsPeserta', 250)->nullable();
            $table->string('code', 50)->nullable();
            $table->integer('id_dc_sub_asal_pasien')->nullable();
            $table->string('ket_batal', 100)->nullable();
            $table->integer('flag_p2d')->nullable();
            $table->string('memo', 100)->nullable();
            $table->dateTime('tgl_update')->nullable();
            $table->integer('user_update')->nullable();
            $table->char('flag_pending', 10)->nullable();
            $table->integer('flag_pending_bpjs')->nullable();
            $table->string('jasa_kiriman', 1)->nullable();
            $table->string('no_sjp', 100)->nullable();
            $table->integer('user_trma_p2d')->nullable();
            $table->integer('no_urut')->nullable();
            $table->integer('stat_celaka')->nullable();
            $table->integer('flag_jurnal')->nullable();
            $table->integer('flag_coding_inacbg')->nullable();
            $table->integer('daftar_ol')->nullable();
            $table->integer('flag_verif')->nullable();
            $table->integer('user_verif')->nullable();
            $table->string('alasan_batal', 50)->nullable();
            $table->dateTime('tgl_jam_batal')->nullable();
            $table->string('kode_booking', 50)->nullable();
            $table->string('no_antrian_jkn', 50)->nullable();
            $table->integer('flag_checkin')->nullable();
            $table->dateTime('tgl_checkin')->nullable();
            $table->string('nmRujukan', 50)->nullable();
            $table->string('respon_addantrian', 500)->nullable();
            $table->integer('flag_prolanis')->nullable();
            $table->string('provPerujuk', 50)->nullable();
            $table->string('prolanisPRB', 50)->nullable();
            $table->string('hakKelas', 50)->nullable();
            $table->integer('flag_kirim')->nullable();
            $table->string('no_reg_inap', 50)->nullable();
            $table->integer('flag_wa')->nullable();
            $table->text('ttd')->nullable();
            $table->integer('st_fisik')->nullable();
            $table->integer('st_kebiasaan')->nullable();
            $table->text('saran')->nullable();
            $table->integer('status_kes')->nullable();
            $table->integer('id_resum')->nullable();
            $table->dateTime('tgl_hadir')->nullable();
            $table->integer('st_riwayat')->nullable();
            $table->integer('st_lab')->nullable();
            $table->integer('st_rad')->nullable();
            $table->integer('st_ekg')->nullable();
            $table->integer('st_aud')->nullable();
            $table->integer('st_spiro')->nullable();
            $table->integer('flag_kirim_th')->nullable();
            $table->string('kelengkapan_pas', 50)->nullable();
            $table->integer('st_ass_awal')->nullable();
            $table->dateTime('tgl_jam_ass_awal')->nullable();
            $table->integer('id_user_perawat')->nullable();
            $table->integer('st_ass_awal_lanjutan')->nullable();
            $table->dateTime('tgl_jam_ass_awal_lanjutan')->nullable();
            $table->integer('st_ass_dr')->nullable();
            $table->dateTime('tgl_jam_ass_awal_dr')->nullable();
            $table->integer('st_ass_dr_lanjutan')->nullable();
            $table->dateTime('tgl_jam_ass_awal_dr_lanjut')->nullable();
            $table->integer('st_ass_dr_gigi')->nullable();
            $table->integer('st_ass_dr_gigi_lanjutan')->nullable();
            $table->integer('st_ass_perawat_ANC')->nullable();
            $table->integer('id_user_perawat_ANC')->nullable();
            $table->integer('st_ass_perawat_PNC')->nullable();
            $table->dateTime('tgl_jam_ass_perawat_PNC')->nullable();
            $table->integer('id_user_perawat_PNC')->nullable();
            $table->dateTime('tgl_jam_ass_perawat_ANC')->nullable();
            $table->integer('st_dr_anc')->nullable();
            $table->dateTime('tgl_jam_dr_anc')->nullable();
            $table->integer('st_dr_pnc')->nullable();
            $table->dateTime('tgl_jam_dr_pnc')->nullable();
            $table->integer('flag_skd')->nullable();
            $table->integer('flag_skb')->nullable();
            $table->integer('flag_skk')->nullable();
            $table->integer('ft_coding2')->nullable();
            $table->integer('ft_pengantar')->nullable();
            $table->integer('ft_sep')->nullable();
            $table->integer('flag_info')->nullable();
            $table->integer('flag_skh')->nullable();
            $table->integer('flag_sch')->nullable();
            $table->string('info_1', 250)->nullable();
            $table->string('info_2', 250)->nullable();
            $table->integer('st_ass_dr_igd')->nullable();
            $table->dateTime('tgl_jam_dr_igd')->nullable();
            $table->integer('st_ass_awal_fisio')->nullable();
            $table->dateTime('tgl_jam_fisio')->nullable();
            $table->integer('id_user_fisio')->nullable();
            $table->integer('st_ass_inv_fisio')->nullable();
            $table->dateTime('tgl_jam_inv_fisio')->nullable();
            $table->integer('id_user_inv_fisio')->nullable();
            $table->integer('st_ass_awal_hemo')->nullable();
            $table->dateTime('tgl_jam_hemo')->nullable();
            $table->integer('id_user_hemo')->nullable();
            $table->integer('st_ass_inv_hemo')->nullable();
            $table->dateTime('tgl_jam_inv_hemo')->nullable();
            $table->integer('id_user_inv_hemo')->nullable();
            $table->integer('st_ass_plk_hemo')->nullable();
            $table->dateTime('tgl_jam_plk_hemo')->nullable();
            $table->integer('id_user_plk_hemo')->nullable();
            $table->integer('st_usg')->nullable();
            $table->text('ttd_setuju_inap')->nullable();
            $table->string('nama_ttd_inap', 250)->nullable();
            $table->dateTime('tgl_ttd')->nullable();
            $table->integer('id_triase_identitas')->nullable();
            $table->integer('st_kll')->nullable();
            $table->integer('st_serah_terima')->nullable();
            $table->integer('st_rujuk')->nullable();
            $table->string('nama_wali', 250)->nullable();
            $table->text('alamat_wali')->nullable();
            $table->string('no_tlp_wali', 50)->nullable();
            $table->string('hubungan_wali', 250)->nullable();
            $table->string('privasi_1', 250)->nullable();
            $table->string('privasi_2', 250)->nullable();
            $table->string('Umum_ri', 250)->nullable();
            $table->string('Khusus_ri', 250)->nullable();
            $table->string('Bedah_ri', 250)->nullable();
            $table->integer('flag_sk_pasien')->nullable();
            $table->text('ttd_sk_pasien')->nullable();
            $table->dateTime('tgl_sk_pasien')->nullable();
            $table->text('ttd_ri')->nullable();
            $table->integer('flag_rj_ext')->nullable();
            $table->integer('flag_rj_int')->nullable();
            $table->string('ft_coding', 250)->nullable();
            $table->integer('st_ass_luar')->nullable();
            $table->integer('st_ass_dis')->nullable();
            $table->integer('flag_tolak_ri')->nullable();
            $table->dateTime('tgl_tolak_ri')->nullable();
            $table->text('ttd_sk_tolak')->nullable();
            $table->string('nama_kel_ter', 250)->nullable();
            $table->text('nama_almt_kel')->nullable();
            $table->string('tlp_kel', 250)->nullable();
            $table->string('hubungan_kel', 250)->nullable();
            $table->string('umur_wali', 250)->nullable();
            $table->string('jen_kel_wali', 250)->nullable();
            $table->text('al_penolakan_ri')->nullable();
            $table->integer('id_petugas')->nullable();
            $table->string('saksi_1', 250)->nullable();
            $table->text('ttd_saksi_1')->nullable();
            $table->string('saksi_2', 250)->nullable();
            $table->text('ttd_saksi_2')->nullable();
            $table->integer('flag_dr')->nullable();
            $table->dateTime('tgl_verif')->nullable();
            $table->integer('st_ass_ogbyn')->nullable();
            $table->integer('flag_ver_erm')->nullable();
            $table->integer('jeniskunjungan')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tc_registrasi_batal');
    }
};
