<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::unprepared("

CREATE proc [dbo].[inp_tran_sed_RI_sp]
as
update update_kode_bagian_jurnal_v set kode_bagian_asal=kode_bagian_masuk;--untuk kode bagian asal yg kosong
update upd_trans_reg_v set kode_kelompok=kode_kelompok_reg,kode_perusahaan=kode_perusahaan_reg;
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,3 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(3,12,4,15) and kode_bagian like '03%';--TINDAKAN,VISIT,OBSERVASI RUANG RR
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,7 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(14,13) and kode_bagian like '03%';--ASUHAN KEPERAWATAN,SARANA RS
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,1 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(1) and kode_bagian like '03%';--RUANGAN
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,9 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(9,7) and kode_bagian like '03%';--OBAT RUANGAN, OKSIGEN
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,6 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(6) and kode_bagian like '03%';--AMBULANCE
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,10 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(10) and kode_bagian like '03%';--PEMERIKSAAN KELUAR
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,8 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(8) and kode_bagian like '03%';--LAIN - LAIN
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,5 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(5) and kode_bagian like '03%';--SEWA ALAT
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,15 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian_asal as kode_bagian,kode_bagian AS kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(3) and kode_bagian='050101';--lab
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,16 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian_asal as kode_bagian,kode_bagian AS kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(3) and kode_bagian='050201';--rad
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,17 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian_asal AS kode_bagian,kode_bagian AS kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(3) and kode_bagian='050301';--fisio
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,17 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian_asal AS kode_bagian,kode_bagian AS kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(3) and kode_bagian='050401';--HD
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,19 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian_asal AS kode_bagian,kode_bagian AS kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(12) and (kode_bagian like '05%');--PM

insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,19 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian_asal AS kode_bagian,kode_bagian AS kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(3,4,12) and (kode_bagian like '01%' or kode_bagian like '02%');--poli & igd & PM or kode_bagian like '05%'
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,bill_rs as tx_nominal, jumlah,jenis_tindakan,9 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and bill_rs>0 and jenis_tindakan in(7,9) and (kode_bagian like '01%' or kode_bagian like '02%' or kode_bagian like '05%');--bhp poli & igd & PM


--diskon
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,diskon_rs as tx_nominal, jumlah,jenis_tindakan,20 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and diskon_rs>0 and jenis_tindakan in(1) and kode_bagian like '03%';--diskon RUANGAN
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,diskon_rs as tx_nominal, jumlah,jenis_tindakan,22 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian_asal as kode_bagian,kode_bagian AS kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and diskon_rs>0 and jenis_tindakan in(3) and kode_bagian like '05%' ;--disko penunjang medis RI
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,diskon_rs as tx_nominal, jumlah,jenis_tindakan,23 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and diskon_rs>0 and jenis_tindakan in(3,4,14,15) and kode_bagian like '03%';--diskon tindakan RI
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,jenis_tindakan,kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,tgl_input,no_kuitansi,seri_kuitansi,kode_inap) select no_registrasi,no_kunjungan,no_mr,diskon_rs as tx_nominal, jumlah,jenis_tindakan,21 as kode,kode_tc_trans_kasir,kode_barang,nama_tindakan,tgl_jam,kode_dokter1 as kode_dr,kode_trans_far,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,kode_tarif,getdate() as tgl_input,no_kuitansi,seri_kuitansi,kode_inap from v_trans_pelayanan_RI_v where flag_jurnal=0 and diskon_rs>0 and jenis_tindakan in(9,7) ;--diskon OBAT RUANGAN, OKSIGEN


");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE IF EXISTS inp_tran_sed_RI_sp");
    }
};
