<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::unprepared("

CREATE proc [dbo].[inp_tran_selisih_BPJS_RI_sp]
as
update upd_trans_reg_v set kode_kelompok=kode_kelompok_reg,kode_perusahaan=kode_perusahaan_reg;
--1	Ruangan
--2	ICU
--3	Bedah
--4	VK
--5	Tindakan Inap
--6	Jasa Dokter
--7	Resep Apotik
--8	IGD
--9	Poliklinik
--10	Laboratorium
--11	Radiologi
--12	Fisioterapi
--13	Administrasi

--jika selisih minus(-)
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=1 and selisih<0;--RUANGAN
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=3 and selisih<0;--OK
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=4 and selisih<0;--VK
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=5 and selisih<0;--tindakan inap
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=6 and selisih<0;--jasa dokter
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=7 and selisih<0;--resep farmasi
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=8 and selisih<0;--ugd
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=9 and selisih<0;--poliklinik
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=10 and selisih<0;--lab
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=11 and selisih<0;--radiologi
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=12 and selisih<0;--fisio
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,(selisih) as tx_nominal, 1 as jumlah,31 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=13 and selisih<0;--adm

--jika selisih plus(+)
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=1 and selisih>0;--RUANGAN
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=3 and selisih>0;--OK
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=4 and selisih>0;--VK
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=5 and selisih>0;--tindakan inap
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=6 and selisih>0;--jasa dokter
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=7 and selisih>0;--resep farmasi
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=8 and selisih>0;--ugd
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=9 and selisih>0;--poliklinik
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=10 and selisih>0;--lab
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=11 and selisih>0;--radiologi
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=12 and selisih>0;--fisio
insert into tran_sed (no_registrasi,no_kunjungan,no_mr,tx_nominal,jumlah,kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan) select no_registrasi,no_kunjungan,no_mr,selisih as tx_nominal, 1 as jumlah,32 as kode,kode_tc_trans_kasir,nama_tindakan,tgl_jam,kode_bagian,kode_bagian_asal,kode_trans_pelayanan,kode_kelompok,kode_perusahaan,getdate() as tgl_input,no_kuitansi,seri_kuitansi,id_jenis_layanan from v_trans_selisih_BPJS_RI_v where id_jenis_layanan=13 and selisih>0;--adm

");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::unprepared("DROP PROCEDURE IF EXISTS inp_tran_selisih_BPJS_RI_sp");
    }
};
